blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¬ Chat with us on Slack"
    url: https://developer.1password.com/joinslack
    about: Chat with us about shell plugins in our Developer Slack workspace.
  - name: "â“ General 1Password questions"
    url: https://1password.community
    about: I have a question about 1Password that's not directly related to shell plugins.
