blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¬ Chat with us on Slack"
    url: https://join.slack.com/t/1password-devs/shared_invite/zt-1z0rd7lro-fx4LPkQwUF89~PzpDGPe1A
    about: Chat with us about shell plugins in our Developer Slack workspace.
  - name: "â“ General 1Password questions"
    url: https://1password.community
    about: I have a question about 1Password that's not directly related to shell plugins.
